name: Generate Snake

on:
  schedule:
      # Uruchamiaj codziennie o północy
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Generuje animację węża
      - uses: Platane/snk@v3
        with:
          github_user_name: Frigzer
          outputs: dist/github-contribution-grid-snake.svg

      # Publikuje wygenerowany plik na branchu 'output'
      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
